version: 2.1

orbs:
  node: circleci/node@1.1.6

publish: &publish
  working_directory: ~/hoodat-ui
  docker:
    - image: circleci/node:12.16.3
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: npm ci

    - run:
        name: Login into Expo
        command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - publish_to_expo_dev:
            filters:
              branches:
                only: development
        - publish_to_expo_prod:
            filters:
              branches:
                only: master